[project]
name = "reader"
version = "1.1.0"
description = "Extract clean(er), readable text from web pages via trafilatura"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tabulate>=0.10.0",
    "trafilatura>=2.2.0",
]

[tool.pyright]
include = [
    "**/*.py",
]
exclude = [
    ".venv",
    ".git",
    "**/__pycache__/**",
]
venvPath = "."
venv = ".venv"
pythonVersion = "3.13"

[dependency-groups]
dev = [
    "lxml-stubs>=0.5.1",
]
